### ISSUE TITLE
R CMD CHECK

### ISSUE THREAD

**Issue by khufkens** [chuhousen/amerifluxr#22]
HI @chuhousen 

Check if the builds pass with a green flag, if not check the github actions output (or your local check) for errors.

I've one remaining, a non ASCII character in the file amf_download_base.R which I can not find. Could you trace this one to get a green sign again on the CRAN package checks?

**Comment by khufkens** [comment]
For reference NOTES can be argued for, WARNINGS disqualify any package from the get go.

**Comment by chuhousen** [comment]
HI @khufkens 

Sorry for messing it up. Just push to fix the non ASCII issue.
