### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by khufkens** [chuhousen/amerifluxr#3]
Do you have access to the API which runs on the server?

It would be good to have insight into it, and what is and isn't supported. It seems to me that this is a crude stack which returns at times difficult to parse data (i.e. deeply nested JSON - basically a dump of a relational database). This parsing is a pain, and should ideally be avoided as it is tedious to code but also very fragile should the returned data change ever so slightly.

In this context we might have to think about use cases, and restrict what can and can't be queried, to limit our overhead. I'll start a list of obvious things, with some already there (or probably included in code you have written but not yet in the repo).

- [x] site list
- [x] data coverage
- [x] contact info
- [x] variable info
- [ ] data download
- [ ] data summary
- [ ] data visualization (might need another package for this if you want to keep things clean)

**Comment by chuhousen** [comment]
Codes updated for new API
