### ISSUE TITLE
Data policy acknowledgment prompt in a non-interactive environment

### ISSUE THREAD

**Issue by istfer** [chuhousen/amerifluxr#70]
Hi, thank you very much for this package. I'm a user from the [pecan team](https://github.com/PecanProject/), we would like to utilize this package in our Ameriflux pipeline in pecan, I believe you've had some brief exchange with Ankur about this. 

I'm writing to you about this [data policy acknowledgment prompt](https://github.com/chuhousen/amerifluxr/blob/master/R/amf_download_base.R#L175) issue. We would like to run amerifluxr functions in a non-interactive manner. I was wondering if you have any plans for automatized use of this function in the future. I guess we can always modify the code for our purposes on our end, but I wanted to check with you first if you would be willing to consider non-interactive use cases already now. If not, I would also ask if you would consider making any exception for pecan (user), although I can imagine it wouldn't be preferable. 

I thought I would ask because not having to maintain our own version of the package has certain benefits :) What do you think?

Thank you very much for your work once again.
-Istem

**Comment by chuhousen** [comment]
Hi Istem -- Thanks for reaching out. The prompt is meant to mimic the download through UI on the Ameriflux website (https://ameriflux.lbl.gov/data/download-data/), i.e., having users glance and acknowledge data use policy. But I think we should certainly look into options for a non-interactive environment. Do you have any suggestions? 
@khufkens Any suggestion? 
Thanks -- Housen

**Comment by khufkens** [comment]
You can just make this a parameter, if people use the parameter this implicitly implies they agree.

**Comment by chuhousen** [comment]
Thanks for the input. I update the download functions to use agree_policy as a parameter and avoid the interactive prompt.

**Comment by istfer** [comment]
Thank you both very much for your quick response and modification, much appreciated.
